version: '3'
services:
    nextjs-server:
        container_name: web-app-nextjs-sigte
        build:
            context: .
            dockerfile: Dockerfile
        image: web-app-nextjs-sigte:latest
        ports:
            - 9003:9003
